language: php

php:
    - 7.0
    - 5.6

install:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit --config tests/phpunit/phpunit-travis.xml --coverage-clover build/logs/clover.xml;

after_script:
    - php vendor/bin/coveralls -v
